name: MSG
description: A private messaging app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked : ^1.7.6
  observable_ish: ^2.1.4
  provider: ^4.3.2+2
  get_it: ^4.0.1
  google_fonts: ^2.0.0
  intl: ^0.17.0
  flutter_socket_io: ^0.6.0
  country_code_picker: ^2.0.1
  numeric_keyboard: ^1.0.0
  cupertino_icons: ^0.1.3
  dio: ^4.0.0
  shared_preferences: ^2.0.5
  permission_handler: ^6.1.1
  contacts_service: ^0.6.1
  sqflite: ^1.3.1
  path: ^1.8.0
  flutter_spinkit: ^4.1.2+1  
  firebase_core: ^1.0.2
  firebase_messaging: ^10.0.1
  url_launcher: ^6.0.3
  bubble: ^1.1.9+1
  connectivity: ^3.0.3
  data_connection_checker: ^0.3.4
  awesome_notifications: ^0.0.6+9
  flutter_beep: ^0.2.0
  flutter_linkify: ^3.1.3
  flutter_local_notifications: ^5.0.0+4
  image_picker: ^0.7.5+2
  flutter_image_compress: ^1.0.0
  path_provider: ^2.0.2
  fluttertoast: ^8.0.7
  socket_io_client: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Bold.ttf
        - asset: fonts/Ubuntu-Light.ttf
        - asset: fonts/Ubuntu-Medium.ttf
        - asset: fonts/Ubuntu-Regular.ttf
  assets:
    - assets/images/


